/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;


import Validate.Validation;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import DAO.AccountDAO;
import Entity.Account;

/**
 *
 * @author Yaseen Ameer
 */
public class NewSignin extends javax.swing.JFrame {

    /**
     * Creates new form NewSignin
     */
    public NewSignin() {
        initComponents();
        this.setLocationRelativeTo(null);
        jPanel6.setVisible(false);
        btnSearch.setVisible(false);
        btnBack.setVisible(false);
        iconEmail.setVisible(false);
        lblEmail.setVisible(false);
        txtForgotEmail.setVisible(false);
        lblPass1.setVisible(false);
        txtPass1.setVisible(false);
        iconPass1.setVisible(false);
        btnChange.setVisible(false);
        try {

            UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");

        } catch (Exception ex) {
            System.err.println(ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnForgotPass = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        iconPass = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel_SoftZyd = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtCreatePass1 = new javax.swing.JTextField();
        txtCreatePass2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel_inven = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jLabel_inven1 = new javax.swing.JLabel();
        buttonCreateNewUser = new javax.swing.JButton();
        btnSignIn1 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtForgotEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        iconEmail = new javax.swing.JLabel();
        btnChangePass = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        iconPass1 = new javax.swing.JLabel();
        txtPass1 = new javax.swing.JPasswordField();
        lblPass1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUser.setBackground(new java.awt.Color(31, 36, 42));
        txtUser.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        txtUser.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtUserMouseMoved(evt);
            }
        });
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 260, 40));

        txtPass.setBackground(new java.awt.Color(31, 36, 42));
        txtPass.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtPass.setForeground(new java.awt.Color(255, 255, 255));
        txtPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 260, 40));

        btnForgotPass.setBackground(new java.awt.Color(169, 224, 49));
        btnForgotPass.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnForgotPass.setForeground(new java.awt.Color(169, 224, 49));
        btnForgotPass.setText("Forgot Password?");
        btnForgotPass.setBorder(null);
        btnForgotPass.setBorderPainted(false);
        btnForgotPass.setContentAreaFilled(false);
        btnForgotPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnForgotPass.setRequestFocusEnabled(false);
        btnForgotPass.setVerifyInputWhenFocusTarget(false);
        btnForgotPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgotPassActionPerformed(evt);
            }
        });
        jPanel1.add(btnForgotPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 140, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_User_Shield_100px.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Twitter_32px.png"))); // NOI18N
        jButton2.setToolTipText("Twitter");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Twitter_32px_2.png"))); // NOI18N
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 28));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Facebook_32px_2.png"))); // NOI18N
        jButton3.setToolTipText("Facebook");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Facebook_32px_7.png"))); // NOI18N
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 11, -1, 28));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Instagram_32px.png"))); // NOI18N
        jButton4.setToolTipText("Instagram");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Instagram_32px_3.png"))); // NOI18N
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 11, -1, 28));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Secured_Letter_32px.png"))); // NOI18N
        jButton5.setToolTipText("Email");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Secured_Letter_32px_2.png"))); // NOI18N
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 11, -1, 28));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_YouTube_32px.png"))); // NOI18N
        jButton6.setToolTipText("YouTube");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_YouTube_32px_1.png"))); // NOI18N
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 11, -1, 28));

        iconPass.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        iconPass.setForeground(new java.awt.Color(169, 224, 49));
        iconPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Lock_35px.png"))); // NOI18N
        jPanel1.add(iconPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, 45));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(169, 224, 49));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Male_User_35px.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, 45));

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(169, 224, 49));
        jLabel19.setText("Username");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 70, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 172, 150, 0));

        jPanel3.setBackground(new java.awt.Color(31, 36, 42));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_32px.png"))); // NOI18N
        jButton10.setToolTipText("Close");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setRequestFocusEnabled(false);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_30px_3.png"))); // NOI18N
        jButton10.setVerifyInputWhenFocusTarget(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 40, 40));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_32px_1.png"))); // NOI18N
        jButton11.setToolTipText("Minimize");
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setFocusPainted(false);
        jButton11.setRequestFocusEnabled(false);
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_30px_3.png"))); // NOI18N
        jButton11.setVerifyInputWhenFocusTarget(false);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 40, 40));

        jLabel_SoftZyd.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel_SoftZyd.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_SoftZyd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo2hand-removebg-preview (1) (1).png"))); // NOI18N
        jLabel_SoftZyd.setText("2Hand Fashion");
        jPanel3.add(jLabel_SoftZyd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 360, 130));

        jPanel6.setBackground(new java.awt.Color(31, 36, 42));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.setBackground(new java.awt.Color(31, 36, 42));
        txtName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        txtName.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtNameMouseMoved(evt);
            }
        });
        jPanel6.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 330, 40));

        txtEmail.setBackground(new java.awt.Color(31, 36, 42));
        txtEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        txtEmail.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtEmailMouseMoved(evt);
            }
        });
        jPanel6.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 330, 40));

        txtCreatePass1.setBackground(new java.awt.Color(31, 36, 42));
        txtCreatePass1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtCreatePass1.setForeground(new java.awt.Color(255, 255, 255));
        txtCreatePass1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        txtCreatePass1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtCreatePass1MouseMoved(evt);
            }
        });
        jPanel6.add(txtCreatePass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 330, 40));

        txtCreatePass2.setBackground(new java.awt.Color(31, 36, 42));
        txtCreatePass2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtCreatePass2.setForeground(new java.awt.Color(255, 255, 255));
        txtCreatePass2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        txtCreatePass2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtCreatePass2MouseMoved(evt);
            }
        });
        jPanel6.add(txtCreatePass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 330, 40));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(169, 224, 49));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo2hand-removebg-preview (1) (1).png"))); // NOI18N
        jLabel13.setText("2Hand Fashion");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 370, -1));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(169, 224, 49));
        jLabel12.setText(" Inventory Management");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 190, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(169, 224, 49));
        jLabel14.setText("Username");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 90, 20));

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(169, 224, 49));
        jLabel18.setText("Password");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 314, -1));

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(169, 224, 49));
        jLabel17.setText("Confirm Password");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 314, -1));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(169, 224, 49));
        jLabel16.setText("Email");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 314, -1));

        jButton8.setBackground(new java.awt.Color(152, 201, 45));
        jButton8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(21, 25, 28));
        jButton8.setText("Sign up");
        jButton8.setBorder(null);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setFocusPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 330, 40));

        jButton15.setBackground(new java.awt.Color(169, 224, 49));
        jButton15.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton15.setForeground(new java.awt.Color(169, 224, 49));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Back_To_25px.png"))); // NOI18N
        jButton15.setText("Back");
        jButton15.setBorder(null);
        jButton15.setContentAreaFilled(false);
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.setRequestFocusEnabled(false);
        jButton15.setVerifyInputWhenFocusTarget(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 110, -1));

        jLabel_inven.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel_inven.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven.setText("Login Function");
        jPanel6.add(jLabel_inven, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 260, 50));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 410, 560));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 450, 620));

        lblPass.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblPass.setForeground(new java.awt.Color(169, 224, 49));
        lblPass.setText("Password");
        jPanel1.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 110, -1));

        btnSearch.setBackground(new java.awt.Color(152, 201, 45));
        btnSearch.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(21, 25, 28));
        btnSearch.setText("Search");
        btnSearch.setBorder(null);
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setFocusPainted(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 260, 40));

        jLabel_inven1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel_inven1.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven1.setText("Connect with us on");
        jPanel1.add(jLabel_inven1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 120, 20));

        buttonCreateNewUser.setBackground(new java.awt.Color(169, 224, 49));
        buttonCreateNewUser.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        buttonCreateNewUser.setForeground(new java.awt.Color(169, 224, 49));
        buttonCreateNewUser.setText("Create New User");
        buttonCreateNewUser.setBorder(null);
        buttonCreateNewUser.setBorderPainted(false);
        buttonCreateNewUser.setContentAreaFilled(false);
        buttonCreateNewUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCreateNewUser.setRequestFocusEnabled(false);
        buttonCreateNewUser.setVerifyInputWhenFocusTarget(false);
        buttonCreateNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateNewUserActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCreateNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 140, 30));

        btnSignIn1.setBackground(new java.awt.Color(152, 201, 45));
        btnSignIn1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnSignIn1.setForeground(new java.awt.Color(21, 25, 28));
        btnSignIn1.setText("Sign In");
        btnSignIn1.setBorder(null);
        btnSignIn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignIn1.setFocusPainted(false);
        btnSignIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignIn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 260, 40));

        btnBack.setBackground(new java.awt.Color(169, 224, 49));
        btnBack.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(169, 224, 49));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Back_To_25px.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(null);
        btnBack.setContentAreaFilled(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setRequestFocusEnabled(false);
        btnBack.setVerifyInputWhenFocusTarget(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 110, -1));

        txtForgotEmail.setBackground(new java.awt.Color(31, 36, 42));
        txtForgotEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtForgotEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtForgotEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        txtForgotEmail.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtForgotEmailMouseMoved(evt);
            }
        });
        jPanel1.add(txtForgotEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 260, 40));

        lblEmail.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(169, 224, 49));
        lblEmail.setText("Email");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 70, -1));

        iconEmail.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        iconEmail.setForeground(new java.awt.Color(169, 224, 49));
        iconEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Gmail_32px_3.png"))); // NOI18N
        jPanel1.add(iconEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 45));

        btnChangePass.setBackground(new java.awt.Color(169, 224, 49));
        btnChangePass.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnChangePass.setForeground(new java.awt.Color(169, 224, 49));
        btnChangePass.setText("Change Password");
        btnChangePass.setBorder(null);
        btnChangePass.setBorderPainted(false);
        btnChangePass.setContentAreaFilled(false);
        btnChangePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangePass.setRequestFocusEnabled(false);
        btnChangePass.setVerifyInputWhenFocusTarget(false);
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });
        jPanel1.add(btnChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 140, 30));

        btnChange.setBackground(new java.awt.Color(152, 201, 45));
        btnChange.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnChange.setForeground(new java.awt.Color(21, 25, 28));
        btnChange.setText("Change");
        btnChange.setBorder(null);
        btnChange.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChange.setFocusPainted(false);
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });
        jPanel1.add(btnChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 260, 40));

        iconPass1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        iconPass1.setForeground(new java.awt.Color(169, 224, 49));
        iconPass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Lock_35px.png"))); // NOI18N
        jPanel1.add(iconPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, 45));

        txtPass1.setBackground(new java.awt.Color(31, 36, 42));
        txtPass1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtPass1.setForeground(new java.awt.Color(255, 255, 255));
        txtPass1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        jPanel1.add(txtPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 260, 40));

        lblPass1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblPass1.setForeground(new java.awt.Color(169, 224, 49));
        lblPass1.setText("New Password");
        jPanel1.add(lblPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseMoved

    }//GEN-LAST:event_txtUserMouseMoved

    private void btnForgotPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgotPassActionPerformed
        jLabel_SoftZyd.setVisible(true);
        jLabel_inven.setVisible(true);
        jPanel6.setVisible(false);
        btnSearch.setVisible(true);
        btnSignIn1.setVisible(false);
        txtPass.setVisible(false);
        lblPass.setVisible(false);
        iconPass.setVisible(false);
        btnForgotPass.setVisible(false);
        btnBack.setVisible(true);
        iconEmail.setVisible(true);
        lblEmail.setVisible(true);
        txtForgotEmail.setVisible(true);
        btnChangePass.setVisible(false);
        txtUser.setText("");
        txtPass.setText("");

        //       jLabel7.setVisible(false);
        //       jLabel8.setVisible(false);
    }//GEN-LAST:event_btnForgotPassActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

    }//GEN-LAST:event_jButton11ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        jPanel6.setVisible(false);
        jLabel_SoftZyd.setVisible(true);
        jLabel_inven.setVisible(true);
        btnSearch.setVisible(false);
        btnSignIn1.setVisible(true);
        txtPass.setVisible(true);
        lblPass.setVisible(true);
        iconPass.setVisible(true);
        btnForgotPass.setVisible(true);
        btnBack.setVisible(false);
        iconEmail.setVisible(false);
        lblEmail.setVisible(false);
        txtForgotEmail.setVisible(false);
        btnChangePass.setVisible(true);
        buttonCreateNewUser.setVisible(true);
        lblPass1.setVisible(false);
        txtPass1.setVisible(false);
        iconPass1.setVisible(false);
        btnChange.setVisible(false);
        txtUser.setText("");
        txtPass.setText("");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        clickSearch();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButton11MouseClicked

    private void buttonCreateNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateNewUserActionPerformed
        jLabel_SoftZyd.setVisible(false);
        jLabel_inven.setVisible(false);
        jPanel6.setVisible(true);
        txtUser.setText("");
        txtPass.setText("");
    }//GEN-LAST:event_buttonCreateNewUserActionPerformed

    private void btnSignIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignIn1ActionPerformed
        clickLogin();
    }//GEN-LAST:event_btnSignIn1ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        jPanel6.setVisible(false);
        jLabel_SoftZyd.setVisible(true);
        jLabel_inven.setVisible(true);
        btnSearch.setVisible(false);
        btnSignIn1.setVisible(true);
        txtPass.setVisible(true);
        lblPass.setVisible(true);
        iconPass.setVisible(true);
        btnForgotPass.setVisible(true);
        btnBack.setVisible(false);
        iconEmail.setVisible(false);
        lblEmail.setVisible(false);
        txtForgotEmail.setVisible(false);
        btnChangePass.setVisible(true);
        txtUser.setText("");
        txtPass.setText("");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        createAcc();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtCreatePass2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCreatePass2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreatePass2MouseMoved

    private void txtCreatePass1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCreatePass1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreatePass1MouseMoved

    private void txtEmailMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailMouseMoved

    private void txtNameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameMouseMoved

    private void txtForgotEmailMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtForgotEmailMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtForgotEmailMouseMoved

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        btnSignIn1.setVisible(false);
        btnForgotPass.setVisible(false);
        buttonCreateNewUser.setVisible(false);
        btnBack.setVisible(true);
        btnChangePass.setVisible(false);
        lblPass1.setVisible(true);
        txtPass1.setVisible(true);
        iconPass1.setVisible(true);
        btnChange.setVisible(true);
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        clickChange();
    }//GEN-LAST:event_btnChangeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewSignin().setVisible(true);
            }
        });
    }

    private boolean vildateChange() {
        if (Validation.iEmpty(txtUser, "User không được để trống")) {
            return true;
        }
        if (Validation.iEmpty(txtPass, "Mật khẩu không được để trống")) {
            return true;
        }
        if (Validation.iEmpty(txtPass1, "Mật khẩu mới không được để trống")) {
            return true;
        }
        return false;
    }

    private boolean validateForgot() {
        if (Validation.iEmpty(txtUser, "User không được để trống")) {
            return true;
        }
        if (Validation.iEmpty(txtForgotEmail, "Email không được để trống")) {
            return true;
        }
        if (Validation.isNotEmail(txtForgotEmail, "Sai định dạng email")) {
            return true;
        }
        return false;
    }

    private boolean validateSignIn() {
        if (Validation.iEmpty(txtUser, "User không được để trống")) {
            return true;
        }
        if (Validation.iEmpty(txtPass, "Password không được để trống")) {
            return true;
        }
        return false;
    }
    private boolean validateCreate() {
        if (Validation.iEmpty(txtName, "Tên đăng nhập không được để trống")) {
            return true;
        }
        if (Validation.iEmpty(txtEmail, "Email không được để trống")) {
            return true;
        }
        if (Validation.isNotEmail(txtEmail, "Sai định dạng email")) {
            return true;
        }
        if (Validation.iEmpty(txtCreatePass1, "Mật khẩu không được để trống")) {
            return true;
        }
        if (Validation.iEmpty(txtCreatePass2, "Nhập lại mật khẩu")) {
            return true;
        }
        if (!txtCreatePass1.getText().equalsIgnoreCase(txtCreatePass2.getText())) {
            JOptionPane.showMessageDialog(this, "Mật khẩu không khớp");
            return true;
        }
        return false;
    }
    private boolean clickSearch() {
        AccountDAO accD = new AccountDAO();
        if (validateForgot()) {
            return true;
        }
        try {
            List<Account> listAcc = accD.selectAll();
            boolean login = false;
            for (Account x : listAcc) {

                if (x.getUser().equalsIgnoreCase(txtUser.getText())) {
                    if (x.getEmail().equalsIgnoreCase(txtForgotEmail.getText())) {
                        login = true;
                        String i;
                        do {
                            i = JOptionPane.showInputDialog(this, "Nhập mật khẩu mới");
                            System.out.println(i);
                            if (i.isEmpty()) {
                                JOptionPane.showMessageDialog(this, "MK không được để trống", "Error", JOptionPane.ERROR_MESSAGE);
                            }
                        } while (i.isEmpty());
                        String user = x.getUser();
                        String pass = i;
                        accD.update(pass,user);
                        JOptionPane.showMessageDialog(this, "Đổi mk thành công");
                        txtUser.setText("");
                        txtPass.setText("");
                        txtForgotEmail.setText("");
                    }
                }

            }
            if (login == false) {
                JOptionPane.showMessageDialog(this, "Tên tài khoản và email không khớp", "Error", JOptionPane.ERROR_MESSAGE);
                return true;
            }
        } catch (Exception ex) {
            Logger.getLogger(NewSignin.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    private boolean clickLogin() {
        AccountDAO accD = new AccountDAO();
        if (validateSignIn()) {
            return true;
        }
        try {
            List<Account> listAcc = accD.selectAll();
            boolean login = false;
            for (Account x : listAcc) {

                if (x.getUser().equalsIgnoreCase(txtUser.getText())) {
                    if (x.getPass().equalsIgnoreCase(txtPass.getText())) {
                        JOptionPane.showMessageDialog(this, "Đăng nhập thành công");
                        login = true;
                        this.dispose();
                        if (x.getRole() == 0) {
                            new ViewQuanLy().setVisible(true);
                        }
                        if (x.getRole() == 1) {
                            new ViewNhanVien().setVisible(true);
                        }
                        if (x.getRole() == 2) {
                            new ViewKhachHanh().setVisible(true);
                        }
                    }
                }

            }
            if (login == false) {
                JOptionPane.showMessageDialog(this, "Tên tài khoản hoặc mật khẩu không đúng", "Error", JOptionPane.ERROR_MESSAGE);
                return true;
            }
        } catch (Exception ex) {
            Logger.getLogger(NewSignin.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;

    }

    private boolean clickChange() {
        if (vildateChange()) {
            return true;
        }
        AccountDAO accD = new AccountDAO();
        try {
            List<Account> listAcc = accD.selectAll();
            boolean login = false;
            for (Account x : listAcc) {

                if (x.getUser().equalsIgnoreCase(txtUser.getText())) {
                    if (x.getPass().equalsIgnoreCase(txtPass.getText())) {
                        x.setPass(txtPass1.getText());
                        System.out.println(x.getPass());
                        accD.update(x.getPass(),x.getUser());
                        JOptionPane.showMessageDialog(this, "Đổi mk thành công");
                        txtPass.setText("");
                        txtPass1.setText("");
                        txtUser.setText("");

                        return true;
                    }
                }

            }
            if (login == false) {
                JOptionPane.showMessageDialog(this, "Tên tài khoản hoặc mật khẩu không đúng", "Error", JOptionPane.ERROR_MESSAGE);
                return true;
            }
        } catch (Exception ex) {
            Logger.getLogger(NewSignin.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    

    private boolean createAcc() {
        AccountDAO accD = new AccountDAO();
        if (validateCreate()) {
            return true;
        }
        try {
            Account acc = new Account();
            acc.setUser(txtName.getText());
            acc.setPass(txtCreatePass1.getText());
            acc.setEmail(txtEmail.getText());
            acc.setRole(2);

         List<Account> x = accD.selectAll();
            for (Account a : x) {

                if (a.getUser().equalsIgnoreCase(txtName.getText())) {
                    JOptionPane.showMessageDialog(this, "Tên tài khoản đã tồn tại");
                    return true;
                }
            } 

            accD.insert(acc);
            txtCreatePass1.setText("");
            txtName.setText("");
            txtEmail.setText("");
            txtCreatePass2.setText("");
            JOptionPane.showMessageDialog(this, "Tạo tài khoản thành công");
            return true;

        } catch (Exception e) {
        }
        return false;
    }

    private boolean checkLogin() {

        return false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnForgotPass;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSignIn1;
    private javax.swing.JButton buttonCreateNewUser;
    private javax.swing.JLabel iconEmail;
    private javax.swing.JLabel iconPass;
    private javax.swing.JLabel iconPass1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_SoftZyd;
    private javax.swing.JLabel jLabel_inven;
    private javax.swing.JLabel jLabel_inven1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPass1;
    private javax.swing.JTextField txtCreatePass1;
    private javax.swing.JTextField txtCreatePass2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtForgotEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPass1;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
